export const moodSamples = [
  "Today, I am as lost as a phone signal in a lift… here, but barely useful",
  "I feel like that Abey yaar! you say when Zomato delivers your food late.",
  "Somewhere between 'Main kya karoon? Job chhod doon kya?' and 'Chal beta, aish karenge' ",
  "Mood: 'Shaadi karungi toh Kareena wale lehenga mein hi!'… overconfident with zero logic.",
  "Feeling like that last piece of Kaju Katli during Diwali… waiting to be picked but no one's noticing.",
  "I'm feeling like 'Main apni favorite hoon,' but no one else seems to agree!",
  "Feeling like 'Main aisa kyun hoon?' from *Lakshya*… absolutely no idea what I'm doing!",
  "Feeling like *Kabir Singh*—a little toxic, a little intense, but mostly missing my ex.",
  "Feeling like *Govinda* in any 90s movie… over-the-top, colorful, and slightly chaotic.",
  "Feeling like *Mogambo* today—happy when things go my way, but ready to say 'Mogambo khush nahi hai' any second.",
  "I feel like *Rajpal Yadav* in any movie—small in role but big in drama!",
  "Today's vibe: 'Picture abhi baaki hai mere dost!' but feeling like the credits are about to roll.",
  "I'm in a *Bahubali* mode—thinking 'Why did Kattappa kill Bahubali?' but also realizing it's irrelevant to my life.",
  "Today's vibe: 'Ye bik gayi hai gormint!'… everything's going haywire!",
  "Today's vibe is like when your 'npm install' takes longer than the time it took to write the code.",
  "I'm feeling like the '500 Internal Server Error'—something's wrong, but I don't know what.",
  "I'm in a 'Ctrl + C, Ctrl + V' mood—hoping the code works just because I've done it a hundred times before.",
  "I'm as lost as when I try to figure out how 'this' works in JavaScript after reading 5 tutorials.",
  "My day's like writing a 1000-line React component and realizing you forgot to import the stylesheet.",
  "I'm like 'try/catch'—always expecting errors, but not prepared to handle them.",
  "I feel like *Gaitonde* after successfully deploying my project—'Kabhi Kabhi lagta hai apunich bhagwan hai!'",
  "I'm like a developer who just fixed a critical bug and now feeling like a superhero. ",
  "Feeling like an absolute champ after finding the one missing semicolon that broke the whole app.",
];
